import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Search from '../components/Search'
import Weather from '../components/Weather'

export default function Home() {

  const [weatherData, setWeatherData] = useState('');

  const onSearchDataHandler = enteredSearchData => {
    setWeatherData(enteredSearchData);
  }

    return (
      <div>
        <Head>
          <title>Weather App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* Overlay */}
        <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/20 z-[1]' />

        {/* Background Image */}
        <Image
          src='https://images.unsplash.com/photo-1500964757637-c85e8a162699?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2406&q=80'
          layout='fill'
          className='object-cover'
        />

        {/* Search */}
        <Search onSaveSearchData={onSearchDataHandler}/>

        {/* Weather */}
        {weatherData.location && weatherData.current && <Weather data={weatherData} />}
      </div>
    )
  }
